INSERT INTO BOOK (AUTHOR,BOOKSTATUS,DEPARTMENT,TITLE ) VALUES ('Jane Austen','AVAILABLE','ADULT','Emma');
INSERT INTO BOOK (AUTHOR,BOOKSTATUS,DEPARTMENT,TITLE ) VALUES ('Jane Austen','AVAILABLE','ADULT','Pride & Prejudice');
INSERT INTO BOOK (AUTHOR,BOOKSTATUS,DEPARTMENT,TITLE ) VALUES ('Jane Austen','AVAILABLE','ADULT','Sense and Sensibility');
INSERT INTO BOOK (AUTHOR,BOOKSTATUS,DEPARTMENT,TITLE ) VALUES ('J.K. Rowling','AVAILABLE','ADULT','Harry Potter and the Philosophers Stone'); -- Philosopher\'s Stone
INSERT INTO BOOK (AUTHOR,BOOKSTATUS,DEPARTMENT,TITLE ) VALUES ('J.K. Rowling','AVAILABLE','ADULT','Harry Potter and the Chamber of Secrets');
INSERT INTO BOOK (AUTHOR,BOOKSTATUS,DEPARTMENT,TITLE ) VALUES ('J.K. Rowling','AVAILABLE','ADULT','Harry Potter and the Prisoner of Azkaban');
INSERT INTO BOOK (AUTHOR,BOOKSTATUS,DEPARTMENT,TITLE ) VALUES ('Albert Einstein','AVAILABLE','ADULT','On the Generalized Theory of Gravitation');
